### ISSUE TITLE
Use Yarn workspaces and lerna

### ISSUE THREAD

**Issue by echarles** [jtpio/jupyterlab-extension-examples#15]
As the number of examples grows and we introduce example dependencies, it may be useful to use a system like [yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces) completed by [lerna](https://lerna.js.org) - see e.g. [this blog post](https://medium.com/hy-vee-engineering/creating-a-monorepo-with-lerna-yarn-workspaces-cf163908965d).

**Comment by jtpio** [comment]
Good idea, this will also make it easier to build all the examples at once with a root `package.json` / `lerna.json` :+1: 

However lerna can be "yet another tool" to learn for many people, so we should keep it possible to build the examples one by one in each folder with the usual `jlpm && jupyter labextension link .`

**Comment by echarles** [comment]
@jtpio just opened #16 .- I will do more work tomorrow on this. Looking for your feedback.

**Comment by jtpio** [comment]
Fixed by #16
