### ISSUE TITLE
Snippets from code

### ISSUE THREAD

**Issue by fcollonval** [jtpio/jupyterlab-extension-examples#20]
One of the hard part with examples is to maintain the snippets in README in sync with the testable code. Would it be interesting to use one of the following solutions (or another one - I looked quickly on the web for that problem)?

https://github.com/NativeScript/markdown-snippet-injector
https://github.com/zakhenry/embedme

**Comment by jtpio** [comment]
That sounds like a great idea :+1: 

The second one looks good and even support partial snippets (line range).
