### ISSUE TITLE
tsconfig questions

### ISSUE THREAD

**Issue by fcollonval** [jtpio/jupyterlab-extension-examples#30]
Hey, I got two questions about the typescript configuration for the examples:

* We are not using the same options than the extension template, not the Jupyterlab core. Would it be better to use options as close as possible?
* Currently example tsconfig files point to a to level file. Would it be better to keep all the configuration in each example folder? That would allow interested people to start from a copy-paste of an example?

**Comment by jtpio** [comment]
Good catch, it makes sense to stay close to the cookiecutter and JupyterLab code.

I think the main reason it is like this for now was to facilitate the migration to 1.0 (#1).

Happy to remove the base config, and that would indeed make it easier to keep the examples self-contained.

**Comment by echarles** [comment]
There are pro (self contained examples) and cons (risk of divergence if we don't update all examples) to remove the base conf. I am ok to remove the base.

We can progress to ensure the base config as close as possible to jlab then remove the base.

**Comment by jtpio** [comment]
Should the `tsconfig` files be identical for all examples? If so we can ensure that with CI.

**Comment by jtpio** [comment]
> Should the `tsconfig` files be identical for all examples? If so we can ensure that with CI.

For example with something like this:

```bash
$ find . -name "tsconfig.json" | xargs diff --from-file
```

**Comment by echarles** [comment]
CI enforcement sounds like a good idea. We could relax with excludes later if needed.
