### ISSUE TITLE
Add state example

### ISSUE THREAD

**Issue by fcollonval** [jtpio/jupyterlab-extension-examples#32]
The common extension points don't list state. I think it is an important example to add.

**Comment by jtpio** [comment]
Good idea :+1:

**Comment by echarles** [comment]
Quick comment (which is valid for all extensions): an image showing the extension would be great.

See e.g. on https://github.com/microsoft/vscode-extension-samples

```
You can expect from each sample:

    An explanation of its functionality
    A gif or screenshot demonstrating its usage
    Link to a guide on VS Code website, if it has one
    Listing of used VS Code API and Contribution Points
    Code of the same style, enforced using TSLint
```
