### ISSUE TITLE
packages lock files

### ISSUE THREAD

**Issue by fcollonval** [jtpio/jupyterlab-extension-examples#35]
Currently the examples have a package-lock.json that is unused as we used jlpm to follow Jupyterlab recommendation. But there is no yarn.lock neither. The question is: it seems logical to remove the npm lock file but should we replace it with a yarn lock file?

**Comment by jtpio** [comment]
I think it's fine for now to not have any lock files.

So we can indeed remove all package-lock.json without adding a yarn.lock.
