### ISSUE TITLE
JupyterLab style convention

### ISSUE THREAD

**Issue by jtpio** [jtpio/jupyterlab-extension-examples#4]
JupyterLab has a style convention guide in the wiki: https://github.com/jupyterlab/jupyterlab/wiki/TypeScript-Style-Guide.

We should try to follow it whenever possible when updating the examples, so it's easier for the developers looking for extra examples to also navigate the source code of the core extensions.

**Comment by echarles** [comment]
Should we introduce a linter based on the [JupyterLab lint definition](https://github.com/jupyterlab/jupyterlab/blob/master/tslint.json)?

**Comment by jtpio** [comment]
Sounds good :+1: 

And also add `prettier` for code formatting.

**Comment by fcollonval** [comment]
@jtpio @echarles I think this can now be closed.

**Comment by echarles** [comment]
+1

**Comment by jtpio** [comment]
Yes, thanks!
