### ISSUE TITLE
Switch from tslint to eslint

### ISSUE THREAD

**Issue by fcollonval** [jtpio/jupyterlab-extension-examples#49]
`tslint` is being deprecated. We should switch to `eslint`.

References:
https://github.com/typescript-eslint/tslint-to-eslint-config
https://github.com/typescript-eslint/typescript-eslint

**Comment by jtpio** [comment]
Another reference, ipywidgets recently moved to ESLint: https://github.com/jupyter-widgets/ipywidgets/pull/2657

**Comment by fcollonval** [comment]
Thanks @jtpio 
I play a bit on this one today. I'll submit a PR later this week.

**Comment by jtpio** [comment]
Thanks @fcollonval, that would be great!

It seemed like TypeScript 3.8 made the lint check fail (see  https://github.com/jtpio/jupyterlab-extension-examples/pull/70#issuecomment-592138423 and https://github.com/jtpio/jupyterlab-extension-examples/runs/473121876).

So switching to ESLint will hopefully make it easier to migrate to TypeScript 3.8 after.
