### ISSUE TITLE
Rename the repo to jupyterlab-extension-examples?

### ISSUE THREAD

**Issue by jtpio** [jtpio/jupyterlab-extension-examples#5]
This name might give a better idea of the content.

But this could be done only when we consider moving it to the `jupyterlab` organization.

**Comment by echarles** [comment]
I like `jupyterlab-extension-examples` as it says what it is: a loosely list of examples each focussing  on a specific area.

We can wait to move to jupyterlab, but sooner is better. It is still time to do that today :)

**Comment by jtpio** [comment]
Done!
