### ISSUE TITLE
Add Binder link

### ISSUE THREAD

**Issue by jtpio** [jtpio/jupyterlab-extension-examples#6]
It would be great to add a Binder link, so it becomes possible to try the examples and look at the end result before even looking at the code.

In the `postBuild` file we would link to all the extensions:

```bash
jlpm && jlpm build && \
jupyter labextension link \
   hello_world \
   commands_and_menus \
   ...
```

**Comment by echarles** [comment]
This depends if the extensions example are supposed to be enable all at once (no overlap...)

Is it one binder link for all or one binder per example?

**Comment by jtpio** [comment]
It would be one binder for all.

Same as if we install them all locally in the same environment.

**Comment by jtpio** [comment]
As for the overlap, maybe the examples could be designed in such a way that they don't overlap too much?

**Comment by echarles** [comment]
They should be designed in such a way. We can write a bit about that on the root README to shed some light for the user on which extension and why he should enable them.

Maybe later creating some groups of examples would make sense.
