### ISSUE TITLE
Detach the fork from the base repo?

### ISSUE THREAD

**Issue by jtpio** [jtpio/jupyterlab-extension-examples#61]
Since there is no plan to merge the changes back to upstream, and we eventually will move it under the `jupyterlab` organization, I would suggest detaching the fork from the base repo.

This would also ensure the commits get correctly shown for everyone:

https://help.github.com/en/github/setting-up-and-managing-your-github-profile/why-are-my-contributions-not-showing-up-on-my-profile#commit-was-made-in-a-fork

Additionally we can add a mention to https://github.com/MMesch/labextension_tutorial in the README for credits.

@fcollonval @echarles what do you think?

**Comment by echarles** [comment]
:+1: Sure, this makes sense. Detaching with a mention in README is OK. Not sure how [deforking easy is](https://github.community/t5/How-to-use-Git-and-GitHub/De-forking-a-Github-repo/td-p/2785).

**Comment by jtpio** [comment]
From: https://help.github.com/en/github/setting-up-and-managing-your-github-profile/why-are-my-contributions-not-showing-up-on-my-profile#commit-was-made-in-a-fork

"To detach the fork and turn it into a standalone repository on GitHub, contact GitHub Support "

**Comment by fcollonval** [comment]
Agree also that it makes sense to detach the repository and to keep a mention for the nice work of @MMesch
