### ISSUE TITLE
Update the `serving_files` extension to JLab 1

### ISSUE THREAD

**Issue by jtpio** [jtpio/jupyterlab-extension-examples#7]
The [serving_files](https://github.com/jtpio/jupyterlab-extension-tutorial/tree/master/serving_files) extensions was not updated in #1.

Changes involve modifying `tsconfig.json`, `package.json` and using the `JupyterFrontEnd` and `JupyterFrontEndPlugin` tokens (see #1 for an example).

**Comment by fcollonval** [comment]
Do we really want this one to be included? What do we expect it to bring compare to the server extension example?

**Comment by echarles** [comment]
IMHO this can be removed. StaticFileHandler is a special case. If we want to keep a trace of that, we could add an handler in the `server-extension` example.
PS: There is a rest of `myserverextension` which can also be removed.

**Comment by jtpio** [comment]
Also fine to remove :+1: (especially now that we have a nice server extension example)

**Comment by fcollonval** [comment]
@echarles Thanks for seeing that one. I open a fix in #55
