### ISSUE TITLE
Update LICENSE

### ISSUE THREAD

**Issue by jtpio** [jtpio/jupyterlab-extension-examples#74]
For now the current license is "The Unlicense".

Ideally we would update it to the "BSD 3-Clause License", which is the one used by most of the other Jupyter projects. 

I think @fcollonval raised that question before. Is there anything special we should do before updating? I suppose we could open the PR and gather the opinion of everyone who contributed until now (4 people as of today), and merge it if we all agree.

What do you think?

cc @echarles

**Comment by echarles** [comment]
`BSD 3-Clause License`, `Apache License 2.0` or `MIT License` make sense to me.

**Comment by fcollonval** [comment]
I think `BSD 3-Clause` is the better choice to align with the other jupyter project. And we definitely need the agreement of all participants and especially of @MMesch as he sets the current license.
